"""add is_shown and is_new flags and added_hours column to the apps_list table

Revision ID: 83c98a6a77bc
Revises: a68bee411496
Create Date: 2026-07-30 17:41:37.254178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83c98a6a77bc'
down_revision: Union[str, Sequence[str], None] = 'a68bee411496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps_list', sa.Column('added_hours', sa.Integer(), server_default='0', nullable=False))
    op.add_column('apps_list', sa.Column('is_shown', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('apps_list', sa.Column('is_new', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps_list', 'added_hours')
    op.drop_column('apps_list', 'is_new')
    op.drop_column('apps_list', 'is_shown')
    # ### end Alembic commands ###
